### PR TITLE
Add constituent array interface

### PR DESCRIPTION
**Pull request by peverwhee**
Interface added, but test not added - I'm having problems with the test failing because the gfortran version on izumi is too old to have some of the necessary features (like deferred-length characters and "final" routines).

### CODE REVIEW

**Comment by gold2718** [comment]
> gfortran version on izumi is too old to have some of the necessary features (like deferred-length characters and "final" routines).

What version are you using? I have tests of deferred-length strings that run fine on Izumi. Also, I thought 'final' has been supported since about gfortran 4.9.

**Comment by peverwhee** [comment]
@gold2718 "The Fortran compiler identification is GNU 4.8.5"

I am unsure how to change what version it's using...

**Comment by gold2718** [comment]
> @gold2718 "The Fortran compiler identification is GNU 4.8.5"
> 
> I am unsure how to change what version it's using...

I usually peek in the ccs_config/machines/config_machines.xml file to see what module is being loaded for CESM runs. Another technique is to us
```
module avail 2>&1 | grep compiler
```
to see the compiler options. Also, on Izumi, I think `module load compiler/gnu` loads a default new(ish) version. That is what I was using in my testing.

**Review by gold2718 — APPROVED** [review]
I think this is good, thanks!

**Pull request merged**
